name: Veridoctor CI/CD

on:
  push:
    branches:
      - main
      - dev
      - uat
  workflow_dispatch:

# add linting, formatting and testing jobs
jobs:
  # web builds
  build_deploy_web_development:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    environment: development
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to develop
        run: |
          docker-build veridoctor-web dev ./apps/web/Dockerfile /home/veridoctor/veridoctor/env/.client-dev.env.sh -y

  build_deploy_web_uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: self-hosted
    environment: uat
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to uat
        run: |
          docker-build veridoctor-web uat ./apps/web/Dockerfile -y

  build_deploy_web_production:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to production
        run: |
          docker-build veridoctor-web prod ./apps/web/Dockerfile -y

  # provider app builds
  build_deploy_provider_app_development:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    environment: development
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to develop
        run: |
          docker-build providerapp dev ./apps/provider/Dockerfile -y

  build_deploy_provider_app_uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: self-hosted
    environment: uat
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to uat
        run: |
          docker-build providerapp uat ./apps/provider/Dockerfile -y

  build_deploy_provider_app_production:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to production
        run: |
          docker-build providerapp prod ./apps/provider/Dockerfile -y

  # facility app builds
  build_deploy_facility_app_development:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    environment: development
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to develop
        run: |
          docker-build facilityapp dev ./apps/facility/Dockerfile -y

  build_deploy_facility_app_uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: self-hosted
    environment: uat
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to uat
        run: |
          docker-build facilityapp uat ./apps/facility/Dockerfile -y

  build_deploy_facility_app_production:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to production
        run: |
          docker-build facilityapp prod ./apps/facility/Dockerfile /home/veridoctor/veridoctor/env/.client-dev.env.sh -y

  # health portal app builds
  build_deploy_health_portal_app_development:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    environment: development
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to develop
        run: |
          docker-build healthportal dev ./apps/health-portal/Dockerfile -y

  build_deploy_health_portal_uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: self-hosted
    environment: uat
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to uat
        run: |
          docker-build healthportal uat ./apps/health-portal/Dockerfile -y

  build_deploy_health_portal_production:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v7
      - name: Build and deploy to production
        run: |
          docker-build healthportal prod ./apps/health-portal/Dockerfile -y
